/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveScore extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.LiveScoreRecord> {

	private static final long serialVersionUID = -146480676;

	/**
	 * The singleton instance of <code>pickem.live_score</code>
	 */
	public static final com.nflpickem.database.schema.tables.LiveScore LIVE_SCORE = new com.nflpickem.database.schema.tables.LiveScore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.LiveScoreRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.LiveScoreRecord.class;
	}

	/**
	 * The column <code>pickem.live_score.id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.live_score.version</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.live_score.json</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.String> JSON = createField("json", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>pickem.live_score.week_number</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.Integer> WEEK_NUMBER = createField("week_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>pickem.live_score</code> table reference
	 */
	public LiveScore() {
		this("live_score", null);
	}

	/**
	 * Create an aliased <code>pickem.live_score</code> table reference
	 */
	public LiveScore(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE);
	}

	private LiveScore(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.LiveScoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private LiveScore(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.LiveScoreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.Long> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_LIVE_SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LiveScoreRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_LIVE_SCORE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LiveScoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LiveScoreRecord>>asList(com.nflpickem.database.schema.Keys.KEY_LIVE_SCORE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.LiveScore as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.LiveScore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.LiveScore rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.LiveScore(name, null);
	}
}
