/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Logs extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.LogsRecord> {

	private static final long serialVersionUID = 1014699464;

	/**
	 * The singleton instance of <code>pickem.logs</code>
	 */
	public static final com.nflpickem.database.schema.tables.Logs LOGS = new com.nflpickem.database.schema.tables.Logs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.LogsRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.LogsRecord.class;
	}

	/**
	 * The column <code>pickem.logs.log_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LogsRecord, org.jooq.types.UInteger> LOG_ID = createField("log_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>pickem.logs.time_stamp</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LogsRecord, java.sql.Timestamp> TIME_STAMP = createField("time_stamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>pickem.logs.logger</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LogsRecord, java.lang.String> LOGGER = createField("logger", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.logs.priority</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LogsRecord, java.lang.String> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.logs.message</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.LogsRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.CLOB.length(65535).nullable(false), this, "");

	/**
	 * Create a <code>pickem.logs</code> table reference
	 */
	public Logs() {
		this("logs", null);
	}

	/**
	 * Create an aliased <code>pickem.logs</code> table reference
	 */
	public Logs(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.Logs.LOGS);
	}

	private Logs(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.LogsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Logs(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.LogsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.LogsRecord, org.jooq.types.UInteger> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_LOGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LogsRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_LOGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LogsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LogsRecord>>asList(com.nflpickem.database.schema.Keys.KEY_LOGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.Logs as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.Logs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.Logs rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.Logs(name, null);
	}
}
