/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PicksExtendedPivot extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord> {

	private static final long serialVersionUID = 540924061;

	/**
	 * The singleton instance of <code>pickem.picks_extended_pivot</code>
	 */
	public static final com.nflpickem.database.schema.tables.PicksExtendedPivot PICKS_EXTENDED_PIVOT = new com.nflpickem.database.schema.tables.PicksExtendedPivot();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord.class;
	}

	/**
	 * The column <code>pickem.picks_extended_pivot.player_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord, java.lang.Long> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.picks_extended_pivot.Game1</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord, java.lang.String> GAME1 = createField("Game1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.picks_extended_pivot.Game2</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord, java.lang.String> GAME2 = createField("Game2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.picks_extended_pivot.Game3</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord, java.lang.String> GAME3 = createField("Game3", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>pickem.picks_extended_pivot</code> table reference
	 */
	public PicksExtendedPivot() {
		this("picks_extended_pivot", null);
	}

	/**
	 * Create an aliased <code>pickem.picks_extended_pivot</code> table reference
	 */
	public PicksExtendedPivot(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT);
	}

	private PicksExtendedPivot(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord> aliased) {
		this(alias, aliased, null);
	}

	private PicksExtendedPivot(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.PicksExtendedPivot as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.PicksExtendedPivot(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.PicksExtendedPivot rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.PicksExtendedPivot(name, null);
	}
}
