/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PicksExtended extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.PicksExtendedRecord> {

	private static final long serialVersionUID = 1130392933;

	/**
	 * The singleton instance of <code>pickem.picks_extended</code>
	 */
	public static final com.nflpickem.database.schema.tables.PicksExtended PICKS_EXTENDED = new com.nflpickem.database.schema.tables.PicksExtended();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.PicksExtendedRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.PicksExtendedRecord.class;
	}

	/**
	 * The column <code>pickem.picks_extended.player_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedRecord, java.lang.Long> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.picks_extended.Game1</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedRecord, java.lang.String> GAME1 = createField("Game1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.picks_extended.Game2</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedRecord, java.lang.String> GAME2 = createField("Game2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.picks_extended.Game3</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PicksExtendedRecord, java.lang.String> GAME3 = createField("Game3", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>pickem.picks_extended</code> table reference
	 */
	public PicksExtended() {
		this("picks_extended", null);
	}

	/**
	 * Create an aliased <code>pickem.picks_extended</code> table reference
	 */
	public PicksExtended(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.PicksExtended.PICKS_EXTENDED);
	}

	private PicksExtended(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PicksExtendedRecord> aliased) {
		this(alias, aliased, null);
	}

	private PicksExtended(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PicksExtendedRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.PicksExtended as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.PicksExtended(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.PicksExtended rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.PicksExtended(name, null);
	}
}
