/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pick extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.PickRecord> {

	private static final long serialVersionUID = -709635602;

	/**
	 * The singleton instance of <code>pickem.pick</code>
	 */
	public static final com.nflpickem.database.schema.tables.Pick PICK = new com.nflpickem.database.schema.tables.Pick();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.PickRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.PickRecord.class;
	}

	/**
	 * The column <code>pickem.pick.id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.pick.version</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.pick.game_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.pick.is_correct</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Boolean> IS_CORRECT = createField("is_correct", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * The column <code>pickem.pick.offensive_yards</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Double> OFFENSIVE_YARDS = createField("offensive_yards", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>pickem.pick.over_under</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Double> OVER_UNDER = createField("over_under", org.jooq.impl.SQLDataType.FLOAT, this, "");

	/**
	 * The column <code>pickem.pick.player_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.pick.team</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.String> TEAM = createField("team", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.pick.week_number</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Integer> WEEK_NUMBER = createField("week_number", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>pickem.pick</code> table reference
	 */
	public Pick() {
		this("pick", null);
	}

	/**
	 * Create an aliased <code>pickem.pick</code> table reference
	 */
	public Pick(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.Pick.PICK);
	}

	private Pick(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PickRecord> aliased) {
		this(alias, aliased, null);
	}

	private Pick(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PickRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_PICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_PICK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord>>asList(com.nflpickem.database.schema.Keys.KEY_PICK_PRIMARY, com.nflpickem.database.schema.Keys.KEY_PICK_GAME_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.Pick as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.Pick(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.Pick rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.Pick(name, null);
	}
}
