/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Player extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.PlayerRecord> {

	private static final long serialVersionUID = 2086609133;

	/**
	 * The singleton instance of <code>pickem.player</code>
	 */
	public static final com.nflpickem.database.schema.tables.Player PLAYER = new com.nflpickem.database.schema.tables.Player();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.PlayerRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.PlayerRecord.class;
	}

	/**
	 * The column <code>pickem.player.id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player.version</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player.account_expired</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Boolean> ACCOUNT_EXPIRED = createField("account_expired", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player.account_locked</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Boolean> ACCOUNT_LOCKED = createField("account_locked", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player.address1</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> ADDRESS1 = createField("address1", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.address2</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> ADDRESS2 = createField("address2", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.city</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.default_pick</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> DEFAULT_PICK = createField("default_pick", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player.email</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player.enabled</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player.first_name</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player.last_name</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player.password</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player.password_expired</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Boolean> PASSWORD_EXPIRED = createField("password_expired", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player.state</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.username</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player.zip</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> ZIP = createField("zip", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.app_sessionid</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> APP_SESSIONID = createField("app_sessionid", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.device_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>pickem.player.registration_key</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.String> REGISTRATION_KEY = createField("registration_key", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>pickem.player</code> table reference
	 */
	public Player() {
		this("player", null);
	}

	/**
	 * Create an aliased <code>pickem.player</code> table reference
	 */
	public Player(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.Player.PLAYER);
	}

	private Player(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PlayerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Player(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PlayerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Long> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_PLAYER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_PLAYER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord>>asList(com.nflpickem.database.schema.Keys.KEY_PLAYER_PRIMARY, com.nflpickem.database.schema.Keys.KEY_PLAYER_EMAIL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.Player as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.Player(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.Player rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.Player(name, null);
	}
}
