/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerActivity extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> {

	private static final long serialVersionUID = -351407620;

	/**
	 * The singleton instance of <code>pickem.player_activity</code>
	 */
	public static final com.nflpickem.database.schema.tables.PlayerActivity PLAYER_ACTIVITY = new com.nflpickem.database.schema.tables.PlayerActivity();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.PlayerActivityRecord.class;
	}

	/**
	 * The column <code>pickem.player_activity.id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player_activity.version</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player_activity.ip_address</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.String> IP_ADDRESS = createField("ip_address", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.player_activity.is_logged_in</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Boolean> IS_LOGGED_IN = createField("is_logged_in", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player_activity.last_activity_date</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.sql.Timestamp> LAST_ACTIVITY_DATE = createField("last_activity_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>pickem.player_activity.player_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Long> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>pickem.player_activity</code> table reference
	 */
	public PlayerActivity() {
		this("player_activity", null);
	}

	/**
	 * Create an aliased <code>pickem.player_activity</code> table reference
	 */
	public PlayerActivity(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY);
	}

	private PlayerActivity(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> aliased) {
		this(alias, aliased, null);
	}

	private PlayerActivity(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Long> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_PLAYER_ACTIVITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_PLAYER_ACTIVITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord>>asList(com.nflpickem.database.schema.Keys.KEY_PLAYER_ACTIVITY_PRIMARY, com.nflpickem.database.schema.Keys.KEY_PLAYER_ACTIVITY_PLAYER_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.PlayerActivity as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.PlayerActivity(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.PlayerActivity rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.PlayerActivity(name, null);
	}
}
