/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRole extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> {

	private static final long serialVersionUID = 2058031736;

	/**
	 * The singleton instance of <code>pickem.player_role</code>
	 */
	public static final com.nflpickem.database.schema.tables.PlayerRole PLAYER_ROLE = new com.nflpickem.database.schema.tables.PlayerRole();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.PlayerRoleRecord.class;
	}

	/**
	 * The column <code>pickem.player_role.role_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRoleRecord, java.lang.Long> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.player_role.player_id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.PlayerRoleRecord, java.lang.Long> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>pickem.player_role</code> table reference
	 */
	public PlayerRole() {
		this("player_role", null);
	}

	/**
	 * Create an aliased <code>pickem.player_role</code> table reference
	 */
	public PlayerRole(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE);
	}

	private PlayerRole(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> aliased) {
		this(alias, aliased, null);
	}

	private PlayerRole(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_PLAYER_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRoleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRoleRecord>>asList(com.nflpickem.database.schema.Keys.KEY_PLAYER_ROLE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.PlayerRole as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.PlayerRole(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.PlayerRole rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.PlayerRole(name, null);
	}
}
