/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegistrationCode extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> {

	private static final long serialVersionUID = -1142093480;

	/**
	 * The singleton instance of <code>pickem.registration_code</code>
	 */
	public static final com.nflpickem.database.schema.tables.RegistrationCode REGISTRATION_CODE = new com.nflpickem.database.schema.tables.RegistrationCode();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.RegistrationCodeRecord.class;
	}

	/**
	 * The column <code>pickem.registration_code.id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.registration_code.date_created</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.sql.Timestamp> DATE_CREATED = createField("date_created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>pickem.registration_code.token</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>pickem.registration_code.username</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>pickem.registration_code</code> table reference
	 */
	public RegistrationCode() {
		this("registration_code", null);
	}

	/**
	 * Create an aliased <code>pickem.registration_code</code> table reference
	 */
	public RegistrationCode(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE);
	}

	private RegistrationCode(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> aliased) {
		this(alias, aliased, null);
	}

	private RegistrationCode(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.lang.Long> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_REGISTRATION_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_REGISTRATION_CODE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord>>asList(com.nflpickem.database.schema.Keys.KEY_REGISTRATION_CODE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.RegistrationCode as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.RegistrationCode(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.RegistrationCode rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.RegistrationCode(name, null);
	}
}
