/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role extends org.jooq.impl.TableImpl<com.nflpickem.database.schema.tables.records.RoleRecord> {

	private static final long serialVersionUID = 793499258;

	/**
	 * The singleton instance of <code>pickem.role</code>
	 */
	public static final com.nflpickem.database.schema.tables.Role ROLE = new com.nflpickem.database.schema.tables.Role();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.nflpickem.database.schema.tables.records.RoleRecord> getRecordType() {
		return com.nflpickem.database.schema.tables.records.RoleRecord.class;
	}

	/**
	 * The column <code>pickem.role.id</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RoleRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.role.version</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RoleRecord, java.lang.Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>pickem.role.authority</code>.
	 */
	public final org.jooq.TableField<com.nflpickem.database.schema.tables.records.RoleRecord, java.lang.String> AUTHORITY = createField("authority", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>pickem.role</code> table reference
	 */
	public Role() {
		this("role", null);
	}

	/**
	 * Create an aliased <code>pickem.role</code> table reference
	 */
	public Role(java.lang.String alias) {
		this(alias, com.nflpickem.database.schema.tables.Role.ROLE);
	}

	private Role(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.RoleRecord> aliased) {
		this(alias, aliased, null);
	}

	private Role(java.lang.String alias, org.jooq.Table<com.nflpickem.database.schema.tables.records.RoleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.nflpickem.database.schema.Pickem.PICKEM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.nflpickem.database.schema.tables.records.RoleRecord, java.lang.Long> getIdentity() {
		return com.nflpickem.database.schema.Keys.IDENTITY_ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord> getPrimaryKey() {
		return com.nflpickem.database.schema.Keys.KEY_ROLE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord>>asList(com.nflpickem.database.schema.Keys.KEY_ROLE_PRIMARY, com.nflpickem.database.schema.Keys.KEY_ROLE_AUTHORITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.nflpickem.database.schema.tables.Role as(java.lang.String alias) {
		return new com.nflpickem.database.schema.tables.Role(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.nflpickem.database.schema.tables.Role rename(java.lang.String name) {
		return new com.nflpickem.database.schema.tables.Role(name, null);
	}
}
