/**
 * This class is generated by jOOQ
 */
package com.votabulary.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in votabulary
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table votabulary.member
	 */
	public static final com.votabulary.database.schema.tables.Member MEMBER = com.votabulary.database.schema.tables.Member.MEMBER;
}
