/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FaqRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.FaqRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1698900599;

	/**
	 * Setter for <code>pickem.faq.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.faq.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.faq.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.faq.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.faq.html_answer</code>.
	 */
	public void setHtmlAnswer(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.faq.html_answer</code>.
	 */
	public java.lang.String getHtmlAnswer() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>pickem.faq.question</code>.
	 */
	public void setQuestion(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.faq.question</code>.
	 */
	public java.lang.String getQuestion() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>pickem.faq.faq_type</code>.
	 */
	public void setFaqType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>pickem.faq.faq_type</code>.
	 */
	public java.lang.String getFaqType() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.Faq.FAQ.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.Faq.FAQ.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.nflpickem.database.schema.tables.Faq.FAQ.HTML_ANSWER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.nflpickem.database.schema.tables.Faq.FAQ.QUESTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.nflpickem.database.schema.tables.Faq.FAQ.FAQ_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getHtmlAnswer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getQuestion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getFaqType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FaqRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FaqRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FaqRecord value3(java.lang.String value) {
		setHtmlAnswer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FaqRecord value4(java.lang.String value) {
		setQuestion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FaqRecord value5(java.lang.String value) {
		setFaqType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FaqRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FaqRecord
	 */
	public FaqRecord() {
		super(com.nflpickem.database.schema.tables.Faq.FAQ);
	}

	/**
	 * Create a detached, initialised FaqRecord
	 */
	public FaqRecord(java.lang.Long id, java.lang.Long version, java.lang.String htmlAnswer, java.lang.String question, java.lang.String faqType) {
		super(com.nflpickem.database.schema.tables.Faq.FAQ);

		setValue(0, id);
		setValue(1, version);
		setValue(2, htmlAnswer);
		setValue(3, question);
		setValue(4, faqType);
	}
}
