/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.GameRecord> implements org.jooq.Record12<java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 276072269;

	/**
	 * Setter for <code>pickem.game.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.game.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.game.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.game.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.game.away_score</code>.
	 */
	public void setAwayScore(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.game.away_score</code>.
	 */
	public java.lang.Integer getAwayScore() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>pickem.game.away_team</code>.
	 */
	public void setAwayTeam(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.game.away_team</code>.
	 */
	public java.lang.String getAwayTeam() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>pickem.game.game_time</code>.
	 */
	public void setGameTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>pickem.game.game_time</code>.
	 */
	public java.sql.Timestamp getGameTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>pickem.game.home_score</code>.
	 */
	public void setHomeScore(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>pickem.game.home_score</code>.
	 */
	public java.lang.Integer getHomeScore() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>pickem.game.home_team</code>.
	 */
	public void setHomeTeam(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>pickem.game.home_team</code>.
	 */
	public java.lang.String getHomeTeam() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>pickem.game.line</code>.
	 */
	public void setLine(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>pickem.game.line</code>.
	 */
	public java.lang.Double getLine() {
		return (java.lang.Double) getValue(7);
	}

	/**
	 * Setter for <code>pickem.game.offensive_yards</code>.
	 */
	public void setOffensiveYards(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>pickem.game.offensive_yards</code>.
	 */
	public java.lang.Double getOffensiveYards() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>pickem.game.over_under</code>.
	 */
	public void setOverUnder(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>pickem.game.over_under</code>.
	 */
	public java.lang.Double getOverUnder() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>pickem.game.week_number</code>.
	 */
	public void setWeekNumber(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>pickem.game.week_number</code>.
	 */
	public java.lang.Integer getWeekNumber() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>pickem.game.game_type</code>.
	 */
	public void setGameType(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>pickem.game.game_type</code>.
	 */
	public java.lang.String getGameType() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Long, java.lang.Long, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.Game.GAME.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.Game.GAME.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.nflpickem.database.schema.tables.Game.GAME.AWAY_SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.nflpickem.database.schema.tables.Game.GAME.AWAY_TEAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.nflpickem.database.schema.tables.Game.GAME.GAME_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.nflpickem.database.schema.tables.Game.GAME.HOME_SCORE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.nflpickem.database.schema.tables.Game.GAME.HOME_TEAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field8() {
		return com.nflpickem.database.schema.tables.Game.GAME.LINE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field9() {
		return com.nflpickem.database.schema.tables.Game.GAME.OFFENSIVE_YARDS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field10() {
		return com.nflpickem.database.schema.tables.Game.GAME.OVER_UNDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.nflpickem.database.schema.tables.Game.GAME.WEEK_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.nflpickem.database.schema.tables.Game.GAME.GAME_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getAwayScore();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAwayTeam();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getGameTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getHomeScore();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getHomeTeam();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value8() {
		return getLine();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value9() {
		return getOffensiveYards();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value10() {
		return getOverUnder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getWeekNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getGameType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value3(java.lang.Integer value) {
		setAwayScore(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value4(java.lang.String value) {
		setAwayTeam(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value5(java.sql.Timestamp value) {
		setGameTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value6(java.lang.Integer value) {
		setHomeScore(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value7(java.lang.String value) {
		setHomeTeam(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value8(java.lang.Double value) {
		setLine(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value9(java.lang.Double value) {
		setOffensiveYards(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value10(java.lang.Double value) {
		setOverUnder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value11(java.lang.Integer value) {
		setWeekNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord value12(java.lang.String value) {
		setGameType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GameRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Integer value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.Integer value6, java.lang.String value7, java.lang.Double value8, java.lang.Double value9, java.lang.Double value10, java.lang.Integer value11, java.lang.String value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GameRecord
	 */
	public GameRecord() {
		super(com.nflpickem.database.schema.tables.Game.GAME);
	}

	/**
	 * Create a detached, initialised GameRecord
	 */
	public GameRecord(java.lang.Long id, java.lang.Long version, java.lang.Integer awayScore, java.lang.String awayTeam, java.sql.Timestamp gameTime, java.lang.Integer homeScore, java.lang.String homeTeam, java.lang.Double line, java.lang.Double offensiveYards, java.lang.Double overUnder, java.lang.Integer weekNumber, java.lang.String gameType) {
		super(com.nflpickem.database.schema.tables.Game.GAME);

		setValue(0, id);
		setValue(1, version);
		setValue(2, awayScore);
		setValue(3, awayTeam);
		setValue(4, gameTime);
		setValue(5, homeScore);
		setValue(6, homeTeam);
		setValue(7, line);
		setValue(8, offensiveYards);
		setValue(9, overUnder);
		setValue(10, weekNumber);
		setValue(11, gameType);
	}
}
