/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveScoreRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.LiveScoreRecord> implements org.jooq.Record4<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -270022173;

	/**
	 * Setter for <code>pickem.live_score.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.live_score.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.live_score.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.live_score.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.live_score.json</code>.
	 */
	public void setJson(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.live_score.json</code>.
	 */
	public java.lang.String getJson() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>pickem.live_score.week_number</code>.
	 */
	public void setWeekNumber(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.live_score.week_number</code>.
	 */
	public java.lang.Integer getWeekNumber() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE.JSON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE.WEEK_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getJson();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getWeekNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiveScoreRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiveScoreRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiveScoreRecord value3(java.lang.String value) {
		setJson(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiveScoreRecord value4(java.lang.Integer value) {
		setWeekNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiveScoreRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LiveScoreRecord
	 */
	public LiveScoreRecord() {
		super(com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE);
	}

	/**
	 * Create a detached, initialised LiveScoreRecord
	 */
	public LiveScoreRecord(java.lang.Long id, java.lang.Long version, java.lang.String json, java.lang.Integer weekNumber) {
		super(com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE);

		setValue(0, id);
		setValue(1, version);
		setValue(2, json);
		setValue(3, weekNumber);
	}
}
