/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PickRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.PickRecord> implements org.jooq.Record9<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Double, java.lang.Double, java.lang.Long, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1406279243;

	/**
	 * Setter for <code>pickem.pick.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.pick.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.pick.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.pick.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.pick.game_id</code>.
	 */
	public void setGameId(java.lang.Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.pick.game_id</code>.
	 */
	public java.lang.Long getGameId() {
		return (java.lang.Long) getValue(2);
	}

	/**
	 * Setter for <code>pickem.pick.is_correct</code>.
	 */
	public void setIsCorrect(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.pick.is_correct</code>.
	 */
	public java.lang.Boolean getIsCorrect() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>pickem.pick.offensive_yards</code>.
	 */
	public void setOffensiveYards(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>pickem.pick.offensive_yards</code>.
	 */
	public java.lang.Double getOffensiveYards() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>pickem.pick.over_under</code>.
	 */
	public void setOverUnder(java.lang.Double value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>pickem.pick.over_under</code>.
	 */
	public java.lang.Double getOverUnder() {
		return (java.lang.Double) getValue(5);
	}

	/**
	 * Setter for <code>pickem.pick.player_id</code>.
	 */
	public void setPlayerId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>pickem.pick.player_id</code>.
	 */
	public java.lang.Long getPlayerId() {
		return (java.lang.Long) getValue(6);
	}

	/**
	 * Setter for <code>pickem.pick.team</code>.
	 */
	public void setTeam(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>pickem.pick.team</code>.
	 */
	public java.lang.String getTeam() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>pickem.pick.week_number</code>.
	 */
	public void setWeekNumber(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>pickem.pick.week_number</code>.
	 */
	public java.lang.Integer getWeekNumber() {
		return (java.lang.Integer) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Double, java.lang.Double, java.lang.Long, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Long, java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Double, java.lang.Double, java.lang.Long, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.Pick.PICK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.Pick.PICK.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field3() {
		return com.nflpickem.database.schema.tables.Pick.PICK.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.nflpickem.database.schema.tables.Pick.PICK.IS_CORRECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return com.nflpickem.database.schema.tables.Pick.PICK.OFFENSIVE_YARDS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field6() {
		return com.nflpickem.database.schema.tables.Pick.PICK.OVER_UNDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return com.nflpickem.database.schema.tables.Pick.PICK.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.nflpickem.database.schema.tables.Pick.PICK.TEAM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.nflpickem.database.schema.tables.Pick.PICK.WEEK_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value3() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getIsCorrect();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getOffensiveYards();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value6() {
		return getOverUnder();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getTeam();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getWeekNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value3(java.lang.Long value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value4(java.lang.Boolean value) {
		setIsCorrect(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value5(java.lang.Double value) {
		setOffensiveYards(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value6(java.lang.Double value) {
		setOverUnder(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value7(java.lang.Long value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value8(java.lang.String value) {
		setTeam(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord value9(java.lang.Integer value) {
		setWeekNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PickRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Long value3, java.lang.Boolean value4, java.lang.Double value5, java.lang.Double value6, java.lang.Long value7, java.lang.String value8, java.lang.Integer value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PickRecord
	 */
	public PickRecord() {
		super(com.nflpickem.database.schema.tables.Pick.PICK);
	}

	/**
	 * Create a detached, initialised PickRecord
	 */
	public PickRecord(java.lang.Long id, java.lang.Long version, java.lang.Long gameId, java.lang.Boolean isCorrect, java.lang.Double offensiveYards, java.lang.Double overUnder, java.lang.Long playerId, java.lang.String team, java.lang.Integer weekNumber) {
		super(com.nflpickem.database.schema.tables.Pick.PICK);

		setValue(0, id);
		setValue(1, version);
		setValue(2, gameId);
		setValue(3, isCorrect);
		setValue(4, offensiveYards);
		setValue(5, overUnder);
		setValue(6, playerId);
		setValue(7, team);
		setValue(8, weekNumber);
	}
}
