/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * VIEW
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PicksExtendedPivotRecord extends org.jooq.impl.TableRecordImpl<com.nflpickem.database.schema.tables.records.PicksExtendedPivotRecord> implements org.jooq.Record4<java.lang.Long, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 224141876;

	/**
	 * Setter for <code>pickem.picks_extended_pivot.player_id</code>.
	 */
	public void setPlayerId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.picks_extended_pivot.player_id</code>.
	 */
	public java.lang.Long getPlayerId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.picks_extended_pivot.Game1</code>.
	 */
	public void setGame1(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.picks_extended_pivot.Game1</code>.
	 */
	public java.lang.String getGame1() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>pickem.picks_extended_pivot.Game2</code>.
	 */
	public void setGame2(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.picks_extended_pivot.Game2</code>.
	 */
	public java.lang.String getGame2() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>pickem.picks_extended_pivot.Game3</code>.
	 */
	public void setGame3(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.picks_extended_pivot.Game3</code>.
	 */
	public java.lang.String getGame3() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT.GAME1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT.GAME2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT.GAME3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGame1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getGame2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getGame3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicksExtendedPivotRecord value1(java.lang.Long value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicksExtendedPivotRecord value2(java.lang.String value) {
		setGame1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicksExtendedPivotRecord value3(java.lang.String value) {
		setGame2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicksExtendedPivotRecord value4(java.lang.String value) {
		setGame3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PicksExtendedPivotRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PicksExtendedPivotRecord
	 */
	public PicksExtendedPivotRecord() {
		super(com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT);
	}

	/**
	 * Create a detached, initialised PicksExtendedPivotRecord
	 */
	public PicksExtendedPivotRecord(java.lang.Long playerId, java.lang.String game1, java.lang.String game2, java.lang.String game3) {
		super(com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT);

		setValue(0, playerId);
		setValue(1, game1);
		setValue(2, game2);
		setValue(3, game3);
	}
}
