/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRoleRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = 1807825936;

	/**
	 * Setter for <code>pickem.player_role.role_id</code>.
	 */
	public void setRoleId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.player_role.role_id</code>.
	 */
	public java.lang.Long getRoleId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.player_role.player_id</code>.
	 */
	public void setPlayerId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.player_role.player_id</code>.
	 */
	public java.lang.Long getPlayerId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE.ROLE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getRoleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRoleRecord value1(java.lang.Long value) {
		setRoleId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRoleRecord value2(java.lang.Long value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRoleRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlayerRoleRecord
	 */
	public PlayerRoleRecord() {
		super(com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE);
	}

	/**
	 * Create a detached, initialised PlayerRoleRecord
	 */
	public PlayerRoleRecord(java.lang.Long roleId, java.lang.Long playerId) {
		super(com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE);

		setValue(0, roleId);
		setValue(1, playerId);
	}
}
