/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerActivityRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Boolean, java.sql.Timestamp, java.lang.Long> {

	private static final long serialVersionUID = 1611828779;

	/**
	 * Setter for <code>pickem.player_activity.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.player_activity.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.player_activity.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.player_activity.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.player_activity.ip_address</code>.
	 */
	public void setIpAddress(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.player_activity.ip_address</code>.
	 */
	public java.lang.String getIpAddress() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>pickem.player_activity.is_logged_in</code>.
	 */
	public void setIsLoggedIn(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.player_activity.is_logged_in</code>.
	 */
	public java.lang.Boolean getIsLoggedIn() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>pickem.player_activity.last_activity_date</code>.
	 */
	public void setLastActivityDate(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>pickem.player_activity.last_activity_date</code>.
	 */
	public java.sql.Timestamp getLastActivityDate() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>pickem.player_activity.player_id</code>.
	 */
	public void setPlayerId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>pickem.player_activity.player_id</code>.
	 */
	public java.lang.Long getPlayerId() {
		return (java.lang.Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Boolean, java.sql.Timestamp, java.lang.Long> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.Boolean, java.sql.Timestamp, java.lang.Long> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.IP_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.IS_LOGGED_IN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.LAST_ACTIVITY_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getIpAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getIsLoggedIn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getLastActivityDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord value3(java.lang.String value) {
		setIpAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord value4(java.lang.Boolean value) {
		setIsLoggedIn(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord value5(java.sql.Timestamp value) {
		setLastActivityDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord value6(java.lang.Long value) {
		setPlayerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerActivityRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.Boolean value4, java.sql.Timestamp value5, java.lang.Long value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlayerActivityRecord
	 */
	public PlayerActivityRecord() {
		super(com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY);
	}

	/**
	 * Create a detached, initialised PlayerActivityRecord
	 */
	public PlayerActivityRecord(java.lang.Long id, java.lang.Long version, java.lang.String ipAddress, java.lang.Boolean isLoggedIn, java.sql.Timestamp lastActivityDate, java.lang.Long playerId) {
		super(com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY);

		setValue(0, id);
		setValue(1, version);
		setValue(2, ipAddress);
		setValue(3, isLoggedIn);
		setValue(4, lastActivityDate);
		setValue(5, playerId);
	}
}
