/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.PlayerRecord> implements org.jooq.Record20<java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1994825358;

	/**
	 * Setter for <code>pickem.player.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.player.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.player.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.player.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.player.account_expired</code>.
	 */
	public void setAccountExpired(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.player.account_expired</code>.
	 */
	public java.lang.Boolean getAccountExpired() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>pickem.player.account_locked</code>.
	 */
	public void setAccountLocked(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.player.account_locked</code>.
	 */
	public java.lang.Boolean getAccountLocked() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>pickem.player.address1</code>.
	 */
	public void setAddress1(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>pickem.player.address1</code>.
	 */
	public java.lang.String getAddress1() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>pickem.player.address2</code>.
	 */
	public void setAddress2(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>pickem.player.address2</code>.
	 */
	public java.lang.String getAddress2() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>pickem.player.city</code>.
	 */
	public void setCity(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>pickem.player.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>pickem.player.default_pick</code>.
	 */
	public void setDefaultPick(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>pickem.player.default_pick</code>.
	 */
	public java.lang.String getDefaultPick() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>pickem.player.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>pickem.player.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>pickem.player.enabled</code>.
	 */
	public void setEnabled(java.lang.Boolean value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>pickem.player.enabled</code>.
	 */
	public java.lang.Boolean getEnabled() {
		return (java.lang.Boolean) getValue(9);
	}

	/**
	 * Setter for <code>pickem.player.first_name</code>.
	 */
	public void setFirstName(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>pickem.player.first_name</code>.
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>pickem.player.last_name</code>.
	 */
	public void setLastName(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>pickem.player.last_name</code>.
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>pickem.player.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>pickem.player.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>pickem.player.password_expired</code>.
	 */
	public void setPasswordExpired(java.lang.Boolean value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>pickem.player.password_expired</code>.
	 */
	public java.lang.Boolean getPasswordExpired() {
		return (java.lang.Boolean) getValue(13);
	}

	/**
	 * Setter for <code>pickem.player.state</code>.
	 */
	public void setState(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>pickem.player.state</code>.
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(14);
	}

	/**
	 * Setter for <code>pickem.player.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>pickem.player.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(15);
	}

	/**
	 * Setter for <code>pickem.player.zip</code>.
	 */
	public void setZip(java.lang.String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>pickem.player.zip</code>.
	 */
	public java.lang.String getZip() {
		return (java.lang.String) getValue(16);
	}

	/**
	 * Setter for <code>pickem.player.app_sessionid</code>.
	 */
	public void setAppSessionid(java.lang.String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>pickem.player.app_sessionid</code>.
	 */
	public java.lang.String getAppSessionid() {
		return (java.lang.String) getValue(17);
	}

	/**
	 * Setter for <code>pickem.player.device_id</code>.
	 */
	public void setDeviceId(java.lang.String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>pickem.player.device_id</code>.
	 */
	public java.lang.String getDeviceId() {
		return (java.lang.String) getValue(18);
	}

	/**
	 * Setter for <code>pickem.player.registration_key</code>.
	 */
	public void setRegistrationKey(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>pickem.player.registration_key</code>.
	 */
	public java.lang.String getRegistrationKey() {
		return (java.lang.String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Long, java.lang.Long, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ACCOUNT_EXPIRED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ACCOUNT_LOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ADDRESS1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ADDRESS2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.DEFAULT_PICK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field10() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field14() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.PASSWORD_EXPIRED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field16() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field17() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.ZIP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field18() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.APP_SESSIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field19() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.DEVICE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return com.nflpickem.database.schema.tables.Player.PLAYER.REGISTRATION_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getAccountExpired();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getAccountLocked();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAddress1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getAddress2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getDefaultPick();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value10() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value14() {
		return getPasswordExpired();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value16() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value17() {
		return getZip();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value18() {
		return getAppSessionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value19() {
		return getDeviceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getRegistrationKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value3(java.lang.Boolean value) {
		setAccountExpired(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value4(java.lang.Boolean value) {
		setAccountLocked(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value5(java.lang.String value) {
		setAddress1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value6(java.lang.String value) {
		setAddress2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value7(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value8(java.lang.String value) {
		setDefaultPick(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value9(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value10(java.lang.Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value11(java.lang.String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value12(java.lang.String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value13(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value14(java.lang.Boolean value) {
		setPasswordExpired(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value15(java.lang.String value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value16(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value17(java.lang.String value) {
		setZip(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value18(java.lang.String value) {
		setAppSessionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value19(java.lang.String value) {
		setDeviceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord value20(java.lang.String value) {
		setRegistrationKey(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PlayerRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Boolean value3, java.lang.Boolean value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.Boolean value10, java.lang.String value11, java.lang.String value12, java.lang.String value13, java.lang.Boolean value14, java.lang.String value15, java.lang.String value16, java.lang.String value17, java.lang.String value18, java.lang.String value19, java.lang.String value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlayerRecord
	 */
	public PlayerRecord() {
		super(com.nflpickem.database.schema.tables.Player.PLAYER);
	}

	/**
	 * Create a detached, initialised PlayerRecord
	 */
	public PlayerRecord(java.lang.Long id, java.lang.Long version, java.lang.Boolean accountExpired, java.lang.Boolean accountLocked, java.lang.String address1, java.lang.String address2, java.lang.String city, java.lang.String defaultPick, java.lang.String email, java.lang.Boolean enabled, java.lang.String firstName, java.lang.String lastName, java.lang.String password, java.lang.Boolean passwordExpired, java.lang.String state, java.lang.String username, java.lang.String zip, java.lang.String appSessionid, java.lang.String deviceId, java.lang.String registrationKey) {
		super(com.nflpickem.database.schema.tables.Player.PLAYER);

		setValue(0, id);
		setValue(1, version);
		setValue(2, accountExpired);
		setValue(3, accountLocked);
		setValue(4, address1);
		setValue(5, address2);
		setValue(6, city);
		setValue(7, defaultPick);
		setValue(8, email);
		setValue(9, enabled);
		setValue(10, firstName);
		setValue(11, lastName);
		setValue(12, password);
		setValue(13, passwordExpired);
		setValue(14, state);
		setValue(15, username);
		setValue(16, zip);
		setValue(17, appSessionid);
		setValue(18, deviceId);
		setValue(19, registrationKey);
	}
}
