/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegistrationCodeRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> implements org.jooq.Record4<java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1875264694;

	/**
	 * Setter for <code>pickem.registration_code.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.registration_code.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.registration_code.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.registration_code.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>pickem.registration_code.token</code>.
	 */
	public void setToken(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.registration_code.token</code>.
	 */
	public java.lang.String getToken() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>pickem.registration_code.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.registration_code.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.sql.Timestamp, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RegistrationCodeRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RegistrationCodeRecord value2(java.sql.Timestamp value) {
		setDateCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RegistrationCodeRecord value3(java.lang.String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RegistrationCodeRecord value4(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RegistrationCodeRecord values(java.lang.Long value1, java.sql.Timestamp value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RegistrationCodeRecord
	 */
	public RegistrationCodeRecord() {
		super(com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE);
	}

	/**
	 * Create a detached, initialised RegistrationCodeRecord
	 */
	public RegistrationCodeRecord(java.lang.Long id, java.sql.Timestamp dateCreated, java.lang.String token, java.lang.String username) {
		super(com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE);

		setValue(0, id);
		setValue(1, dateCreated);
		setValue(2, token);
		setValue(3, username);
	}
}
