/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsRecord extends org.jooq.impl.UpdatableRecordImpl<com.nflpickem.database.schema.tables.records.SettingsRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1369610365;

	/**
	 * Setter for <code>pickem.settings.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>pickem.settings.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>pickem.settings.version</code>.
	 */
	public void setVersion(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>pickem.settings.version</code>.
	 */
	public java.lang.Long getVersion() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>pickem.settings.commish_note</code>.
	 */
	public void setCommishNote(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>pickem.settings.commish_note</code>.
	 */
	public java.lang.String getCommishNote() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>pickem.settings.league_password</code>.
	 */
	public void setLeaguePassword(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>pickem.settings.league_password</code>.
	 */
	public java.lang.String getLeaguePassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>pickem.settings.second_pot_start_week</code>.
	 */
	public void setSecondPotStartWeek(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>pickem.settings.second_pot_start_week</code>.
	 */
	public java.lang.Integer getSecondPotStartWeek() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>pickem.settings.winners_per_week</code>.
	 */
	public void setWinnersPerWeek(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>pickem.settings.winners_per_week</code>.
	 */
	public java.lang.Integer getWinnersPerWeek() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.nflpickem.database.schema.tables.Settings.SETTINGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.nflpickem.database.schema.tables.Settings.SETTINGS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.nflpickem.database.schema.tables.Settings.SETTINGS.COMMISH_NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.nflpickem.database.schema.tables.Settings.SETTINGS.LEAGUE_PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.nflpickem.database.schema.tables.Settings.SETTINGS.SECOND_POT_START_WEEK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.nflpickem.database.schema.tables.Settings.SETTINGS.WINNERS_PER_WEEK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCommishNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getLeaguePassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getSecondPotStartWeek();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getWinnersPerWeek();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value2(java.lang.Long value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value3(java.lang.String value) {
		setCommishNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value4(java.lang.String value) {
		setLeaguePassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value5(java.lang.Integer value) {
		setSecondPotStartWeek(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value6(java.lang.Integer value) {
		setWinnersPerWeek(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.String value4, java.lang.Integer value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SettingsRecord
	 */
	public SettingsRecord() {
		super(com.nflpickem.database.schema.tables.Settings.SETTINGS);
	}

	/**
	 * Create a detached, initialised SettingsRecord
	 */
	public SettingsRecord(java.lang.Long id, java.lang.Long version, java.lang.String commishNote, java.lang.String leaguePassword, java.lang.Integer secondPotStartWeek, java.lang.Integer winnersPerWeek) {
		super(com.nflpickem.database.schema.tables.Settings.SETTINGS);

		setValue(0, id);
		setValue(1, version);
		setValue(2, commishNote);
		setValue(3, leaguePassword);
		setValue(4, secondPotStartWeek);
		setValue(5, winnersPerWeek);
	}
}
