/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>pickem</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.FaqRecord, java.lang.Long> IDENTITY_FAQ = Identities0.IDENTITY_FAQ;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.GameRecord, java.lang.Long> IDENTITY_GAME = Identities0.IDENTITY_GAME;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.Long> IDENTITY_LIVE_SCORE = Identities0.IDENTITY_LIVE_SCORE;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.LogsRecord, org.jooq.types.UInteger> IDENTITY_LOGS = Identities0.IDENTITY_LOGS;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> IDENTITY_PICK = Identities0.IDENTITY_PICK;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Long> IDENTITY_PLAYER = Identities0.IDENTITY_PLAYER;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Long> IDENTITY_PLAYER_ACTIVITY = Identities0.IDENTITY_PLAYER_ACTIVITY;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.lang.Long> IDENTITY_REGISTRATION_CODE = Identities0.IDENTITY_REGISTRATION_CODE;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.RoleRecord, java.lang.Long> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
	public static final org.jooq.Identity<com.nflpickem.database.schema.tables.records.SettingsRecord, java.lang.Long> IDENTITY_SETTINGS = Identities0.IDENTITY_SETTINGS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.FaqRecord> KEY_FAQ_PRIMARY = UniqueKeys0.KEY_FAQ_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.GameRecord> KEY_GAME_PRIMARY = UniqueKeys0.KEY_GAME_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LiveScoreRecord> KEY_LIVE_SCORE_PRIMARY = UniqueKeys0.KEY_LIVE_SCORE_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LogsRecord> KEY_LOGS_PRIMARY = UniqueKeys0.KEY_LOGS_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord> KEY_PICK_PRIMARY = UniqueKeys0.KEY_PICK_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord> KEY_PICK_GAME_ID = UniqueKeys0.KEY_PICK_GAME_ID;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord> KEY_PLAYER_PRIMARY = UniqueKeys0.KEY_PLAYER_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord> KEY_PLAYER_EMAIL = UniqueKeys0.KEY_PLAYER_EMAIL;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> KEY_PLAYER_ACTIVITY_PRIMARY = UniqueKeys0.KEY_PLAYER_ACTIVITY_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> KEY_PLAYER_ACTIVITY_PLAYER_ID = UniqueKeys0.KEY_PLAYER_ACTIVITY_PLAYER_ID;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> KEY_PLAYER_ROLE_PRIMARY = UniqueKeys0.KEY_PLAYER_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> KEY_REGISTRATION_CODE_PRIMARY = UniqueKeys0.KEY_REGISTRATION_CODE_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord> KEY_ROLE_AUTHORITY = UniqueKeys0.KEY_ROLE_AUTHORITY;
	public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.SettingsRecord> KEY_SETTINGS_PRIMARY = UniqueKeys0.KEY_SETTINGS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.FaqRecord, java.lang.Long> IDENTITY_FAQ = createIdentity(com.nflpickem.database.schema.tables.Faq.FAQ, com.nflpickem.database.schema.tables.Faq.FAQ.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.GameRecord, java.lang.Long> IDENTITY_GAME = createIdentity(com.nflpickem.database.schema.tables.Game.GAME, com.nflpickem.database.schema.tables.Game.GAME.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.LiveScoreRecord, java.lang.Long> IDENTITY_LIVE_SCORE = createIdentity(com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE, com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.LogsRecord, org.jooq.types.UInteger> IDENTITY_LOGS = createIdentity(com.nflpickem.database.schema.tables.Logs.LOGS, com.nflpickem.database.schema.tables.Logs.LOGS.LOG_ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.PickRecord, java.lang.Long> IDENTITY_PICK = createIdentity(com.nflpickem.database.schema.tables.Pick.PICK, com.nflpickem.database.schema.tables.Pick.PICK.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.PlayerRecord, java.lang.Long> IDENTITY_PLAYER = createIdentity(com.nflpickem.database.schema.tables.Player.PLAYER, com.nflpickem.database.schema.tables.Player.PLAYER.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.PlayerActivityRecord, java.lang.Long> IDENTITY_PLAYER_ACTIVITY = createIdentity(com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY, com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord, java.lang.Long> IDENTITY_REGISTRATION_CODE = createIdentity(com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE, com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.RoleRecord, java.lang.Long> IDENTITY_ROLE = createIdentity(com.nflpickem.database.schema.tables.Role.ROLE, com.nflpickem.database.schema.tables.Role.ROLE.ID);
		public static org.jooq.Identity<com.nflpickem.database.schema.tables.records.SettingsRecord, java.lang.Long> IDENTITY_SETTINGS = createIdentity(com.nflpickem.database.schema.tables.Settings.SETTINGS, com.nflpickem.database.schema.tables.Settings.SETTINGS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.FaqRecord> KEY_FAQ_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Faq.FAQ, com.nflpickem.database.schema.tables.Faq.FAQ.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.GameRecord> KEY_GAME_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Game.GAME, com.nflpickem.database.schema.tables.Game.GAME.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LiveScoreRecord> KEY_LIVE_SCORE_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE, com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.LogsRecord> KEY_LOGS_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Logs.LOGS, com.nflpickem.database.schema.tables.Logs.LOGS.LOG_ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord> KEY_PICK_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Pick.PICK, com.nflpickem.database.schema.tables.Pick.PICK.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PickRecord> KEY_PICK_GAME_ID = createUniqueKey(com.nflpickem.database.schema.tables.Pick.PICK, com.nflpickem.database.schema.tables.Pick.PICK.GAME_ID, com.nflpickem.database.schema.tables.Pick.PICK.PLAYER_ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord> KEY_PLAYER_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Player.PLAYER, com.nflpickem.database.schema.tables.Player.PLAYER.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRecord> KEY_PLAYER_EMAIL = createUniqueKey(com.nflpickem.database.schema.tables.Player.PLAYER, com.nflpickem.database.schema.tables.Player.PLAYER.EMAIL);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> KEY_PLAYER_ACTIVITY_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY, com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerActivityRecord> KEY_PLAYER_ACTIVITY_PLAYER_ID = createUniqueKey(com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY, com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY.PLAYER_ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.PlayerRoleRecord> KEY_PLAYER_ROLE_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE, com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE.ROLE_ID, com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE.PLAYER_ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RegistrationCodeRecord> KEY_REGISTRATION_CODE_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE, com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord> KEY_ROLE_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Role.ROLE, com.nflpickem.database.schema.tables.Role.ROLE.ID);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.RoleRecord> KEY_ROLE_AUTHORITY = createUniqueKey(com.nflpickem.database.schema.tables.Role.ROLE, com.nflpickem.database.schema.tables.Role.ROLE.AUTHORITY);
		public static final org.jooq.UniqueKey<com.nflpickem.database.schema.tables.records.SettingsRecord> KEY_SETTINGS_PRIMARY = createUniqueKey(com.nflpickem.database.schema.tables.Settings.SETTINGS, com.nflpickem.database.schema.tables.Settings.SETTINGS.ID);
	}
}
