/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pickem extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1235560475;

	/**
	 * The singleton instance of <code>pickem</code>
	 */
	public static final Pickem PICKEM = new Pickem();

	/**
	 * No further instances allowed
	 */
	private Pickem() {
		super("pickem");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.nflpickem.database.schema.tables.Faq.FAQ,
			com.nflpickem.database.schema.tables.Game.GAME,
			com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE,
			com.nflpickem.database.schema.tables.Logs.LOGS,
			com.nflpickem.database.schema.tables.Pick.PICK,
			com.nflpickem.database.schema.tables.PicksExtended.PICKS_EXTENDED,
			com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT,
			com.nflpickem.database.schema.tables.Player.PLAYER,
			com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY,
			com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE,
			com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE,
			com.nflpickem.database.schema.tables.Role.ROLE,
			com.nflpickem.database.schema.tables.Settings.SETTINGS);
	}
}
