/**
 * This class is generated by jOOQ
 */
package com.nflpickem.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in pickem
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table pickem.faq
	 */
	public static final com.nflpickem.database.schema.tables.Faq FAQ = com.nflpickem.database.schema.tables.Faq.FAQ;

	/**
	 * The table pickem.game
	 */
	public static final com.nflpickem.database.schema.tables.Game GAME = com.nflpickem.database.schema.tables.Game.GAME;

	/**
	 * The table pickem.live_score
	 */
	public static final com.nflpickem.database.schema.tables.LiveScore LIVE_SCORE = com.nflpickem.database.schema.tables.LiveScore.LIVE_SCORE;

	/**
	 * The table pickem.logs
	 */
	public static final com.nflpickem.database.schema.tables.Logs LOGS = com.nflpickem.database.schema.tables.Logs.LOGS;

	/**
	 * The table pickem.pick
	 */
	public static final com.nflpickem.database.schema.tables.Pick PICK = com.nflpickem.database.schema.tables.Pick.PICK;

	/**
	 * VIEW
	 */
	public static final com.nflpickem.database.schema.tables.PicksExtended PICKS_EXTENDED = com.nflpickem.database.schema.tables.PicksExtended.PICKS_EXTENDED;

	/**
	 * VIEW
	 */
	public static final com.nflpickem.database.schema.tables.PicksExtendedPivot PICKS_EXTENDED_PIVOT = com.nflpickem.database.schema.tables.PicksExtendedPivot.PICKS_EXTENDED_PIVOT;

	/**
	 * The table pickem.player
	 */
	public static final com.nflpickem.database.schema.tables.Player PLAYER = com.nflpickem.database.schema.tables.Player.PLAYER;

	/**
	 * The table pickem.player_activity
	 */
	public static final com.nflpickem.database.schema.tables.PlayerActivity PLAYER_ACTIVITY = com.nflpickem.database.schema.tables.PlayerActivity.PLAYER_ACTIVITY;

	/**
	 * The table pickem.player_role
	 */
	public static final com.nflpickem.database.schema.tables.PlayerRole PLAYER_ROLE = com.nflpickem.database.schema.tables.PlayerRole.PLAYER_ROLE;

	/**
	 * The table pickem.registration_code
	 */
	public static final com.nflpickem.database.schema.tables.RegistrationCode REGISTRATION_CODE = com.nflpickem.database.schema.tables.RegistrationCode.REGISTRATION_CODE;

	/**
	 * The table pickem.role
	 */
	public static final com.nflpickem.database.schema.tables.Role ROLE = com.nflpickem.database.schema.tables.Role.ROLE;

	/**
	 * The table pickem.settings
	 */
	public static final com.nflpickem.database.schema.tables.Settings SETTINGS = com.nflpickem.database.schema.tables.Settings.SETTINGS;
}
