/**
 * This class is generated by jOOQ
 */
package com.votabulary.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Member extends org.jooq.impl.TableImpl<com.votabulary.database.schema.tables.records.MemberRecord> {

	private static final long serialVersionUID = 1487112750;

	/**
	 * The singleton instance of <code>votabulary.member</code>
	 */
	public static final com.votabulary.database.schema.tables.Member MEMBER = new com.votabulary.database.schema.tables.Member();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.votabulary.database.schema.tables.records.MemberRecord> getRecordType() {
		return com.votabulary.database.schema.tables.records.MemberRecord.class;
	}

	/**
	 * The column <code>votabulary.member.id</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.first_name</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.last_name</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.email</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.state</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.county</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.String> COUNTY = createField("county", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.precinct</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.Integer> PRECINCT = createField("precinct", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>votabulary.member.email_reminder</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.Boolean> EMAIL_REMINDER = createField("email_reminder", org.jooq.impl.SQLDataType.BIT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>votabulary.member.sms_reminder</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.Boolean> SMS_REMINDER = createField("sms_reminder", org.jooq.impl.SQLDataType.BIT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>votabulary.member.sms_number</code>.
	 */
	public final org.jooq.TableField<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.String> SMS_NUMBER = createField("sms_number", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * Create a <code>votabulary.member</code> table reference
	 */
	public Member() {
		this("member", null);
	}

	/**
	 * Create an aliased <code>votabulary.member</code> table reference
	 */
	public Member(java.lang.String alias) {
		this(alias, com.votabulary.database.schema.tables.Member.MEMBER);
	}

	private Member(java.lang.String alias, org.jooq.Table<com.votabulary.database.schema.tables.records.MemberRecord> aliased) {
		this(alias, aliased, null);
	}

	private Member(java.lang.String alias, org.jooq.Table<com.votabulary.database.schema.tables.records.MemberRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.votabulary.database.schema.Votabulary.VOTABULARY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.votabulary.database.schema.tables.records.MemberRecord, java.lang.Long> getIdentity() {
		return com.votabulary.database.schema.Keys.IDENTITY_MEMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.votabulary.database.schema.tables.records.MemberRecord> getPrimaryKey() {
		return com.votabulary.database.schema.Keys.KEY_MEMBER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.votabulary.database.schema.tables.records.MemberRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.votabulary.database.schema.tables.records.MemberRecord>>asList(com.votabulary.database.schema.Keys.KEY_MEMBER_PRIMARY, com.votabulary.database.schema.Keys.KEY_MEMBER_IDX_EMAIL);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.votabulary.database.schema.tables.Member as(java.lang.String alias) {
		return new com.votabulary.database.schema.tables.Member(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.votabulary.database.schema.tables.Member rename(java.lang.String name) {
		return new com.votabulary.database.schema.tables.Member(name, null);
	}
}
